name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: install
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: bui9ld
      run: dotnet build
      
    - name: test
      run: dotnet test
